# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "centos7.6.1810"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.synced_folder ".", "/vagrant_data", disabled: true

  # hostname
  config.vm.hostname = 'helloworld'

  driverletters = ('a'..'z').to_a
  config.vm.provider "libvirt" do |lv|
    # memory and cpu
    lv.memory = 4096
    lv.cpus = 4
    lv.random_hostname = true

    # disks
    # device bus virtio: vba used system disk
    (1..1).each do |idx|
      lv.storage :file, :device => "vd#{driverletters[idx]}", :size => '10G', :bus => "virtio"
    end
    # device bus ide:
    (0..0).each do |idx|
      lv.storage :file, :device => "sd#{driverletters[idx]}", :size => '10G', :bus => "ide"
    end
  end

  # networks
  config.vm.network "private_network", ip: "192.168.1.100"
  config.vm.network "forwarded_port", guest: 80, host: 8081, host_ip: "172.30.126.26"

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    hostname
    cd /etc/yum.repos.d/
    mkdir ./bk
    mv *.repo ./bk
    curl -O http://172.16.134.34/repofiles/queensCentOS76.x86_64.repo
    yum install httpd -y
    systemctl start httpd
  SHELL
end
