[global]
direct=1 
startdelay=10
runtime= 6000
numjobs=1 
ioengine=libaio
iodepth= 64 
size=100G
time_based
filename=/dev/vdb
group_reporting 

;*************************************************

[write_1M]
wait_for_previous 
rw=write 
bs=1M 
name=write_1M_test
description=write_1M_test_description

;*************************************************

[randwrite_4K]
wait_for_previous 
rw=randwrite
bs=4K
name=randwrite_4K_test
description=randwrite_4K_test_description


;*************************************************

[read_1M]
wait_for_previous 
rw=read 
bs=1M 
name=read_1M_test
description=read_1M_test_description

;*************************************************
[randread_4K]
wait_for_previous 
rw=randread
bs=4K
name=randread_4K_test
description=randread_4K_test_description

